
import streamlit as st
import pandas as pd
import numpy as np
import requests
import json
import bz2file as bz2
import pickle
import joblib
from datetime import date, timedelta

today = date.today()
# from ydata_synthetic.synthesizers.regular import RegularSynthesizer
# from ydata_synthetic.synthesizers import ModelParameters, TrainParameters
# from sklearn.preprocessing import LabelEncoder
# from sklearn.model_selection import train_test_split
# from sklearn.linear_model import LogisticRegression
# from sklearn.ensemble import RandomForestClassifier
# from sklearn.neighbors import KNeighborsClassifier
# from sklearn.model_selection import GridSearchCV
# from sklearn.exceptions import NotFittedError
# from sklearn.pipeline import make_pipeline
# from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score


# from collections import defaultdict
# import webbrowser
import joblib

st.set_page_config(layout="wide")
col1,col2,col3,col4 = st.columns(4)


with col1:
    st.image("Images\etl.png",width=150)
    st.subheader("Extract Transform Load") 
    st.caption("ETL is completed")
  
with col2:
    st.image("Images\synthesis.png",width=150)
    st.subheader("Data Synthesis and Generation")
    st.caption("Data Synthesis is done.") 
  
with col3:
   st.image("Images/claimPrediction.png",width=150)
   st.subheader("Risk Score Prediction")
   st.caption("Currently in Claim Prediction") 
   
st.progress(75)


st.title('Claim Prediction')
st.write('This app predicts whether for a given Policy there will be calim or not')
st.header('Enter the following information:')
executive = st.selectbox('Executive', ['JAIKISHIN (S)', 'AMIT', 'RAJENDRA', 'BR', 'MAHESH', 'ASHOK', 'RAJU (S)', 'MANOHAR (S)', 'DIRECT', 'AJI', 'RAHEEM', 'JAIKISHIN (SNC)', 'RENNIE', 'FARHAN', 'MANOHAR', 'MANOHAR (SNC)', 'NELSON', 'AJITHVP', 'AJITH', 'SUVARNA', 'SHADAB/A.RA', 'JOHN', 'UDASI/AF', 'SHADAB/AF', 'JAIKISHIN', 'JOHN/AF', 'NIJIL/AF', 'KEVIN', 'FARHAN/SPS', 'HABEEB/AZM', 'KISHORE/SPS', 'SHADAB', 'AMIT (S)', 'AJITH/SPS', 'RAHEEM/AF', 'SUVARNA/SPS', 'NELSON (S)', 'RENNIE/AF', 'RAHEEM/AAC', 'HABEEB', 'NIJIL', 'AJI/SPS', 'NELSON (SNC)', 'ASHOK (S)', 'UDASI', 'RONALD', 'RAHEEM/AYM', 'RAHEEM/WA', 'RAHEEM/EC', 'KISHORE', 'RAHEEM/AL NBD', 'UDASI/RCRV', 'FARHAN/Y', 'UDASI/DL', 'RENNIE/YOUSUF', 'RAHEEM/AVR', 'AKHIL', 'FARHAN/NAIM', 'RAHEEM/SCM', 'RENNIE/CR', 'CHETAN', 'VIGNESH', 'SUVARNA/VCR', 'NITHEESH', 'ASHOK/RK', 'NIJIL/OASIS CARS', 'AMIT/PB', 'KAJAL', 'FAIZAN', 'SUVARNA/SC', 'SAXENA', 'ANAND', 'AMRUTHA', 'VAIBHAV', 'ASHOK/OK', 'ASHOK/STAIGHT', 'ASHOK/STAIGHT 5', 'FARHAN/A.RA', 'LALIT', 'DANIEL', 'BINDRA', 'RAHUL', 'ALBIN', 'UDASI/SA', 'RENNIE/YOUSUF/MGCARS', 'KHURRAM', 'CHETAN/LALIT DWC', 'AJITH/UDASI DWC', 'HABEEB/DANIEL DWC', 'SUVARNA/AJITHVP DWC', 'RENNIE/VAIBHAV DWC', 'JOHN/RAJU DWC', 'UDASI/ALTAYER', 'JOHN/AJITHVP', 'RENNIE/AJI', 'DANIEL/AJI', 'UDASI/AJI', 'DANIEL/AJITHVP', 'RENNIE/AJITHVP', 'SUVARNA/AJITHVP', 'CHETAN/AJITHVP', 'JOHN/DEALER', 'VAIBHAV/AJI', 'UDASI/AJITHVP', 'AMINAT', 'RAJESH', 'MAHESH/DANIEL DWC', 'VAIBHAV/AJITHVP', 'JOHN/RAJESH DWC', 'MAHESH/DEALER'])

body = st.selectbox('Body', ['SALOON', 'PICK UP', 'VAN', '4 WD', 'MOTOR CYCLE', 'VAN WITH CRANE', 'SUV', 'STATION', 'MINI BUS', 'BUS', 'SPORTS CAR', 'FREEZER PICK-UP', 'SEDAN', 'TRUCK', 'PICK UP TRUCK', 'COUPE', 'HATCH BACK', 'REFRIGERATED PICKUP', 'STATION WAGON', 'MPV', 'FORK LIFT', 'FREEZER VAN', 'PICKUP WITH BOX & TAIL LIFT', 'TRUCK WITH DRY BOX', 'JEEP', 'FREEZER TRUCK', 'AS PER FLEET LIST', 'PICK UP WITH BOX', 'STATION 4 WD', 'TRACTOR HEAD', 'Z-REFRIGERATED VAN', 'Z-BUS', 'TRUCK HEAD', 'Z-2 DOOR', 'WHEEL LOADER', 'TRUCK WITH BOX', 'CRANE', 'CHILLER VAN', 'HEAVY TRUCK', 'Z-DELIVERY VAN', 'Z-TRUCK', 'LOADER', 'LIMOUSINE', 'TRACTOR TRAILOR', 'MOTOR HOME', 'DRILL', 'Z-LOADER', 'TRAILER', 'QUAD BIKE', 'MOTOR BIKE', 'CONVERTIBLE', 'TIPPER PICKUP', 'DUMP TRUCK', 'PICK UP DOUBLE CABIN', 'MICRO BUS 15 Seats', 'MINI VAN', 'LUXURY PICKUP', 'LIGHT PICKUP', 'WATER TANKER', 'EXCAVATOR', 'SALOON STATION ', 'WAGON', 'Z-PANEL VAN', 'TRUCK TRAILOR', 'DOUBLE CABIN', 'TANKER', 'RECOVERY VEHICLE', 'DOOR COUPE', 'TRUCK WITH CRANE', 'AMPHIBIOUS BUS', 'REFRIGERATED VAN', 'SR-150 LOADER', 'Z-REFABRICATED PICK UP', 'TIPPER TRUCK', 'TRUCK/TANKER', 'PIPELAYER', 'MOTOR GRADER', 'Z-BULL DOZER', 'ROLLER', 'CARAVAN', 'PICK UP WITH CRANE', 'SCOOTER', 'PICK UP (REEFER BODY)', 'SC.', 'MOTOR TRICYCLE', 'Z-BOB CAT', 'MINI TRUCK', 'PICKUP WITH TIPPER', 'SC..', 'TRACTOR'])

make = st.selectbox('Make', ['TOYOTA', 'MITSUBISHI', 'HYUNDAI',  'NISSAN', 'BMW', 'ISUZU', 'BAJAJ', 'DAIHATSU', 'KIA', 'HONDA', 'PORSCHE', 'SUZUKI', 'YUTONG', 'KING LONG', 'FORD', 'RANGE ROVER', 'FOTON', 'ROLLS ROYCE', 'LAMBORGHINI', 'JEEP', 'LEXUS', 'MERCURY', 'MAZDA', 'AUDI', 'BUGATTI ', 'HINO', 'CMC', 'PEUGEOT', 'MERCEDES', 'CHEVROLET', 'TATA', 'JAGUAR', 'MERCEDES.', 'FERRARI', 'ROYAL', 'SEAT', 'SUBARU', 'DODGE', 'TOYOTA FORKLIFT', 'VOLVO', 'HUMMER', 'LAND ROVER', 'ASHOK LEYLAND', 'TOYOTA LAND', 'VOLKSWAGEN', 'MINI', 'RENAULT', 'CADILLAC', 'KOMATSU', 'CMC VERYCA', 'VEHICLE AS PER', 'MASERATI', 'LINCOLN', 'GMC', 'YAMAHA', 'BENTLEY ', 'FIAT', 'SANGYONG', 'DAEWOO', 'GREAT WALL', 'SCANIA', 'SHEN LONG ', 'HIGER', 'REACH TRUCK', 'SUNWIN', 'TEREX', 'INDIAN', 'SKODA', 'TADANO', 'VARIOUS VEHICLES', 'T.V.S', 'HARLEY DAVIDSON', 'BRILLIANCE', 'VOLVO.', 'STILL', 'MCLAREN', 'PAGANI', 'MERCEDES-BENZ', 'VESPA', 'KAWASAKI', 'CHRYSLER', 'POLARSUN', 'JCB', 'LOTUS', 'GRAND', 'TRIUMPH', 'MANITOU', 'CASE', 'MANN', 'JUNGHEINRICH', 'R-VISSION', 'VERMEER', 'CATERPILLAR', 'DOOSAN', 'HYSTER', 'JINBEI', 'ALFA ROMEO', 'M.A.N.', 'JMC ', 'GONOW', 'CHERY', 'BOBCAT', 'SAIC', 'BAIC', 'SAAB', 'DELTA ', 'DUCATI', 'EICHER', '-', 'GEELY', 'SMART CAR', 'MG', 'OPEL', 'MAHINDRA', 'PROTON', 'BENELLI', 'KTM', 'LANDMARK', 'GRAND CHEROKEE', 'T G B', 'GODREJ', 'ASTON MARTIN', 'YANGZI', 'OLDS MOBILE', 'FISKER', 'CHL', 'HELLI', 'HAWTAI', 'LUXGEN', 'SKAD', 'MEMON', 'MV', 'JAC', 'MAXTON', 'CLARK', 'FREIGHT LINER', 'CAN', 'BUICK', 'UD', 'ROVER', 'MAXIMAL', 'TVR', 'TCM', 'CITROEN', 'IVECO', 'PONTIAC', 'MAXUS', 'SILVER STON', 'TESLA', 'HYDRA TERRA', 'YALE', 'BYD', 'HARTFORD', 'XIAMEN', 'KATO', 'FUSHUN', 'PROMTRACTOR', 'ZOOMLION', 'CAT', 'DYNAPAC', 'PROLIFT', 'ACURA ', 'LINDE ', 'MV AGUSTA', 'COBRA', 'GAC', 'DONG', 'APRILIA', 'TRAILOR ', 'HECHA', 'PRETON', 'HANCHA', 'LONKING', 'DFSK', 'JMCGL', 'TVS', 'CHANGAN', 'LANDA', '.', 'LANDWIND', 'FORCE', 'SHANTUI', 'CF MOTO', 'FAW', 'HAVAL', 'BOOM TRIKE', 'HERO', 'SAIBAO', 'VICTORY', 'KYMO', 'HYOSUNG', 'MOTO', 'COMBILIFT', 'HC', 'BAOLI', 'CD 30', 'LONG GONG', 'HANGZHOU', 'PIOLET', 'XCMG', 'ASIASTAR', 'DIESEL', 'KINGSTAR', 'AWM', 'INFINITY', 'HAMM', 'GRANDTIGER', 'TRIKE', 'CROWN', 'FORLAND', 'PIAGGIO', 'GS5', 'HANGCHA', 'REDDOT', 'AL AGHADI', 'LIFAN', 'BENTLEY', 'JMC', 'MERCEDES BENZ', 'INFINITI', 'CHERRINGTON', 'WZHOULONG', 'BENDI', 'ZOTYE', 'JANNERLY', 'BUGATTI', 'BONLUCK', 'KEYSTONE', 'SANDSTORM', 'GOLDEN DRAGON', 'HOFMAM', 'ZNA', 'DOMY', 'BORGWARD', 'TELEHANDLER', 'LONDON TAXI', 'SOUEAST', 'MIMA', 'WEIFANG', 'ENERGICA', 'TAILIFT', 'PANOZ AIV'])

model = st.selectbox('Model', ['AVALON', 'CANTER SINGLE CABIN', 'YARIS', 'H-1', 'LANCER', 'ALTIMA', '750 LI', 'COROLLA', 'PRADO', '.', 'SUNNY', 'PULSAR', 'HIACE', 'DISCOVER', 'SANTA-FE', 'HIACE ', '180 CC', 'GRAN MAX', 'PREVIA', 'CAMRY', 'L200', 'SIRION', 'SPORTAGE', 'CR-V', 'CIVIC', 'ECHO', 'CAYENNE', 'ACCORD', 'NKR', 'NPR', 'APV', 'LUXURY', 'XMQ', 'MUSTANG', '204', 'X5', 'VIEW', '740 LI', 'GHOST', 'TIIDA', 'Z8', 'AVENTADOR', 'GRAND CHEROKEE', 'HILUX', 'ES 350', 'MOUNTAINEER', 'ACCENT', '3', 'Q 7', 'CARRERA', 'VEYRON', 'HURACAN', 'LAND CRUISER', 'INNOVA', '745 LI', 'WFR', 'ECOSPORT', 'COASTER', 'CT100', 'PARTNER', 'E350', 'TAHOE', '308', 'EDGE', 'OUTLANDER', 'URVAN VAN', 'STD', 'LP 613', 'CLK-320', 'X-TYPE', 'PICANTO', 'GRAND VITARA', 'GX 460', 'S 500', 'PATROL', 'X-TRAIL', 'DIESEL', 'F430', 'L300', 'RX 300', 'ROSA BUS', 'LX 570', 'SORENTO', 'ENFIELD', 'SPORT SUPER CHARGE', '307', 'TAURUS', 'EPICA', 'AVENGER', '50D- 7AE', 'CBF150S', 'TUCSON', 'CIVIC EXI', 'A 7', 'MONDEO', 'S350', 'TOLIDO', 'FORTUNER', 'RAV 4', 'GETZ', 'PAJERO', 'SENTRA', 'EXPEDITION ', 'F 32 435I', '730 LI', 'ELANTRA', '230 E', '150 CC', 'FUSO', 'BENZ GL63', 'OPTRA', 'INFINITI FX35', 'E 300', 'BLAZER', 'ESCAPE', 'AVEO', 'INFINITI JX 35', 'SPORT', 'QASHQAI', '640 I', 'PATHFINDER', 'I 40', 'LUV', 'CHARGER', 'CAMARO', 'S 40', 'X6', 'A 6', 'LEGACY', 'JUKE', 'H3', 'RIO', 'CAPRICE', 'LR4', 'F-150', '206', 'LUMINA', '6', '350 Z', 'TUNLAND', '1613', 'FOCUS', 'S 350', 'XJ8', 'CRUISER PRADO', 'SILVERADO', 'JETTA', '2400', 'E-25', '207', 'V70', 'SAVANNAH', 'COOPER', 'SLK 300', 'FALCON', '316 I', 'TIGUAN', 'Q 5', 'ODYSSEY', 'SWIFT', 'INFINITI QX56', 'S 280', 'CARNIVAL', 'DUSTER', 'CTS', '200 CC', '200 CLK', 'FORKLIFT', 'RX 350', 'NAVARA', 'RICH', 'PASSAT', 'LAND CRUISER GXR', 'FJ CRUISER', 'CLS 63', 'CIVIC LXI', 'GOLF GTI', 'LS430', '730 IL', 'SPREAD SHEET', 'E25 VAN', 'MURANO', '918 SPIDER', '535 I', '520 (I)', 'IS 250', 'GRANTURISMA', 'ESCALADE', 'H100', 'VIANO', 'CERATO', 'MAXIMA', 'TOWN CAR', 'XF', 'ELENTRA', 'YUKON', 'PILOT', 'CBF150', 'CBF150 MA ', 'LOGAN', 'CX 9', '300 SERIES', '750', 'CITY', 'S 550', '458 SPIDER', 'JAAZ', 'ZENGHGZHOU', 'C 200', 'NATIVA', 'E2000', 'MACAN S', 'CHALLENGER', 'SIENNA', 'RS6', '240 E', 'GT 3.5', 'HD65', 'COROLLA XLI', 'BEETLE', 'URVAN FREEZER VAN', 'CHEROKEE', 'TRAFFIC', 'FLYING SPUR', 'TOUAREG', '330 CI', 'GS 250', 'LPT 613/38', 'LX 470', '500', 'IS300', 'CONTINENTAL GT', 'FH 440', 'XK8', 'ACTYON', 'GT', 'LS 460', 'SLK-200', '2', 'LEXUS ES 350', 'LPO', 'SOUL', 'G55', 'AURION', 'M2S6F', 'FUSION', 'ASX', 'DUTRO ', 'TERCEL', 'CORVETTE', 'OPTIMA', '728 IAL', '3500', 'WINGLE', 'FLEX', '650 I', 'BUS', '520D', 'KLQ6129Q', 'MRV', 'INFINITY', 'SUP', 'CRAFTER', 'GSX', 'SWB 6120', 'VOGUE', 'MICROBUS', 'MT', 'XA', '1316/55', 'SCOUT', 'ZHENZHOU', 'ENVOY', 'CRUZE', 'OCTAVIA', 'LPT', 'XENON', 'HSE', 'INFINITI G35', 'OPIRUS', '530 (I)', 'CLK 280', 'DTS', '200E', '523 I', 'IS 350', 'INFINITY EX 35', 'TR250M', 'ES 300', 'SONATA', 'PANAMERA', 'DURANGO', 'JIMNY', 'SAFRANE', 'CAYMAN', 'AS PER LIST', 'APACHE', 'DAEWOO', 'A 4', 'V ROD', '260', 'MEGANE', 'I 20', 'GALLANT', 'C200', 'SL 500', 'FSV', 'INFINITY G25 S', '911', 'CIAZ', 'FH12', 'REACH', 'VERONA', '599 GTO', 'SLS ROADSTER', 'P1', 'HUAYRA', 'DOUBLE CABIN', 'SONIC', 'ALTO', 'WRANGLER', '4.2', 'CONTINENTAL', 'CIVILION', 'AVANZA', 'S 600 MAYBACH', 'KOLEOS', 'SAVERIO', 'G 63', 'VIRSA', 'GTS 300', 'VN 1700 C', 'S 500 L', 'SEBRING', 'SLQ6503A', 'GS150R', 'A 1', 'R 300', 'INFINITI QX60', 'LEXUS', 'ARMADA', '370Z ', 'ZNA ZHENGZHOU', 'CLA 45 AMG', 'CALIFORNIA', '540-170', 'S-80', 'CLIO', 'RANGER', 'EOS', 'CADENZA', 'VOUGE SE', 'CLC 200', 'SRX', 'M5', '7FBE20', '300C', 'EVORA GTX', 'WRX', 'ATS', 'CABRIO', '320I', 'SX4', 'FH400', 'TERRAIN', 'CLA 250', 'IMPALA', '2040', 'COUNTY', 'MTI', '410', 'LEXUS IS 300', '323 (I)', 'TIIDA SEDAN', 'DUTRO WU410L', '220 CC', 'TRAILOR', 'BOXER', 'E24', 'CBX 250', 'X1', 'GL 63', 'SLS', 'L494', '3008', 'A 8', 'CADDY', 'STRATUS', 'E200', 'XJ', 'CAYENNE S', '404', 'D-MAX', 'BRZ', '300', 'CAMAROO', '328 (I)', 'INFINITY QX70', 'CLS500', '745', 'MK X', '2638', '630I', 'CAPTIVA', 'TRAVERSE', 'CELERIO', 'S-320', 'S 3', 'ES 250', 'R135', 'DP25', 'D30S 5', 'D70 S', 'INFINITI QX80', 'FRV CROSS', 'FD100-7', 'FF', '4RUNNER', 'S-TYPE', 'VELOSTER', '240', 'TRUCK', 'E25 M/BUS', 'ERTIGA GLX', 'OUTBACK', 'ATRRAGE', 'FLUENCE', 'GSR 750 CC', '650S SPIDER', 'CONCRETE MIXER', 'EXPLORER', 'M500XL', 'LS 400', 'RX 100', 'ACCORD EXI', 'GS 300', 'BORA', 'A 3', 'XC-90', '740 (IL)', '323', 'C280', 'S 600', 'XTERRA', 'FD30HT-17', 'T 2600', 'SUBURBAN', 'LION', 'E 50', 'LEXUS RX300', 'E500', 'GOLF', 'HILUX DOUBLE CAB', 'XTS', 'TUNDRA', 'XJ6', 'INFINITY FX45', '120 I', 'ES 330', '645 CI', 'S2000', 'UD TRUCK', 'ASTRO', 'E 55', 'MOUNTAINEER M180', 'ACADIA', 'S 60', 'ML 350', 'DEVILLE', 'CL500', 'FABIA', 'SUPERB', 'LA', 'CCG125 F10', '530 IA', '407', '525 (I)', 'LS 430', 'GLORIA', 'THUNDERBIRD', '400', 'MPV', 'CALIBER', '330 I (SALOON)', '250', 'CAYENNE GTS', 'CBR', '301', 'LOGAN VAN', 'V5', 'E 320', 'CANTER WITH BOX', '300C SRT8', 'SCENIC', 'C240', 'ML350', 'FIESTA', 'KAWASAKI Model', 'TRAIL BLAZER', 'G 500', 'IS F', '750 IL', 'RX20-2D', 'S 5', 'INFINITI Q70', '745 (I)', 'NC700XD', '525 (I) LIMOUSINE', 'A 5 SPORTBACK', 'CL 600', '320', 'GALLOPER', 'SPARK', 'POLO', 'MALIBU', 'LS 460L', 'COOPER COBRA', 'CLS55', 'DELTA', 'ATOS', 'COUPE', '7FD30', 'GL 500', 'C 180', 'ROADKING', 'PETLE', '325 (I)', 'VAN', 'FD 50', 'LR2', 'DISCOVERY', 'SY 6480', 'CLS350', 'XL-7', 'INFINITI I35', 'TREBOT', '220 C', '4.4', 'GSX-R600', 'MICRA', 'LANCER EX', 'INFINITI G37', '112', 'ACCORD LXI', 'INFINITI FX37', 'NEJA', '147', 'GSX 1300 R', 'INFINITI QX4', 'MAGNA', 'NQR', 'LIBERTY', 'CLICK', 'INFINITI G25', 'SL 55', '116 I', 'TT', 'STREAM SI-L', 'GS 460', 'GSXR 1000', 'FZ 1', 'ZX 6R', 'CBR 10000 R9', 'CRUISER SAFARI', 'S350L', 'TROOPER', 'L538', 'SEDONA', 'CLS 500', '2044', 'E240', 'RAPTOR', 'AERIO', 'MONTEGO', 'M.A.N. Model', 'SY 6483A3', 'E5', 'BOULEVARD', 'ULTRA', 'MOHAVE', 'SEQUOIA', 'AVALANCHE 4WD', 'PRIMERA', 'EVOQUE', 'IMPREZA', '528', 'LEXUS LS400', 'E 280', 'RS5', '735 IA', 'VISTA', 'SPORT SC', 'S 63', 'CRUZE LS', 'CLK 500', '230 C', 'GS 430', 'CONTOUR', '528 I', 'S150', 'MG 350', 'MIRAGE GXL', 'MX6', 'A115', 'S 8', 'HAYA BUSA', 'FREEZER P/UP.', 'CARENS', 'PICK-UP WITH CRANE', 'IS 300', 'MG 3', 'LX 323', 'PICK UP', 'YRV', 'HIACE COMMUTER', 'ML 320', '159', 'E-TYPE', 'ZELAS', '09-Mar', 'GRANDIS', '86', 'F-TYPE', 'XJL', 'CX 5', 'SUCCESS', 'FIGO', 'SIERRA', 'FZ 16', 'TERIOS', '118 I', 'BOXTER', 'HD46', 'D21', 'ROZA LW', 'MONSTER 696', 'X3', 'COMPASS', 'LAUREL', '335I', 'RCF', 'VERACRUZ', 'CARINA', 'INFINITY I30', 'BROUGHAM', 'CONTINENTAL GTC V8', 'WRATH', 'ACCORD EX', '500 CL', 'TRIPLE R', 'TRAGET', 'ESCUDO', 'EMGRAND', 'Q 3', 'Z4', 'MERCURY MOUNTAINEER', 'HSE SPORT', 'FLEETWOOD', '125', '360', 'CRUISER FJ', 'CONTINENTAL GTC', '735', 'FREE LANDER', 'NHR', '520', 'SLK 200', 'VICTOR', 'PICK UP ', 'ACCORD V6', '206CC', 'C250', 'ALPINA', 'GENESIS', 'TRAX', 'XKR', 'NAVIGATER', 'I8', 'MG550', 'AUTOBIOGRAPHY', 'FORESTA', 'GL 450', 'OMEGA', 'COMMANDER', 'S400', '200 CD', 'C70', 'CHARADE', 'SYMBOL', 'SCORPIO', 'E320', '300 S', 'BELENO', 'KA24DE', 'SAVANNA', 'F12', '1626', 'RX 8 ', '318', '523 (I)', 'CBR 600 RR', 'FD30T-16', 'GTR', 'L494 3.0 SC HSE S(A)', '650 CI', 'INFINITI QX50', '220E', '208', '508', '318 I', 'GS 350', 'ACCORD LX', 'TIGGO', 'RX 330', '300CE', '605', 'TOPAZ GS', '330i', 'NITRO', 'AVANTE', '560 SEC', 'GLK 250', 'PERSONA', 'RKV200', 'FT 86', 'PATRIOT', '250 A', 'MP4-12C', 'C 250', 'MERCURY', 'VIEW MINI BUS', 'DEFENDER ', 'CRESSIDA', 'CLK 200', '626', '400SE', 'GTS', 'AZERA', 'GHIBLI', 'CAMRY GRANDE', 'CLARUS', 'S280', 'ROCKY', 'CHARGER SALOON', '740(I)', '300 E', 'K2700', 'LINCOLN', 'MAXIMA SALOON', 'INFINITI Q50', 'TRANSPORTER', 'HRV', '740 LIA', 'Z3', 'DUKE', '911 CARRERA S', '728 IL', 'ERTIGA GL', 'H1 SV', 'EXPLORER E343', 'L322', 'V8', 'VITARA', 'SPRINT', 'KB', 'NMR', '650 S', '406 SALOON', 'S1000RR', 'LAND CURISER PRADO', '607', 'SAGA', 'C 300', 'I 10', 'MONTERO', 'VECTRA', 'COUP', 'GRAND MARQUIS', 'M300', '307 COUPE', 'CROWN', '540 IA', 'BLUE BIRD', 'SAFARI', 'SL 63', 'IS 200', 'RENAULT Model', 'A 8L', 'PILOT EXL', 'PICKUP', 'M6', '280 SE', '300 SEL', 'V8  4.6', 'SPRINTER 311', 'JEEP', 'XC70', 'LAREDO', '125 CC', '316', 'APPLAUSE', 'RAM', 'GX 300D', 'SC 400', 'AMG GT S', 'ML 63 AMG', 'GLK 350', 'CIVIC VTI', 'LS', 'IBIZA', 'T-3500', 'MATRIX', 'VENTURE', 'ODESSEY', 'PU DC', 'DBS', 'FINE S/C', 'E 25 P/MT', 'E8', '523', 'STS', 'E 200', 'H3.00XM', 'S 65', 'BF106', 'MOBILE', 'SHADOW', 'R 8', 'A 250', 'RADIUS', '30DF-7', '335 I', 'R1 BIKE', 'JOICE', 'LEXUS RX350', '407 COUPE', 'GRAND VOYAGER', 'E 60', 'I 30', 'LP550', 'MG350', 'CAPRICE LS', 'TERRANO', 'SLK 230', 'RC 350', 'ECLIPSE', 'AS PER LIST ATTACHED', 'LX 450', 'R 500', 'KARAMA', 'E 350 COUPE', 'B 200', 'INVOY', 'H530', 'EDGE SPORT', 'G65', 'FORTUNE', '435 I', '750 I', 'LR3', 'APLANDER', 'S-500L', 'AZURE', 'CPCD30-WS1C', 'ANAG', 'GS 400', 'TACOMA', 'CPD20-FJ2', 'CPCD50-W2C', 'R 6', 'ACCORD COUPE', 'C180', 'REXTON', '5', 'CPCD100', 'SEPHIA', 'CAMRY GLX', 'MERCURY MILAN', 'LAND CRUISER PICK UP', '512', 'INFINITY G37 COUPE', 'B 35', 'SEAT', 'BARINA', '430 E', 'B150', 'GX 470', '535-125', 'F H 12', 'H2', 'INFINITI M35', 'GRAN MOVE', 'LANCER EVOLUTION', 'SPACE WAGON', 'COROLLA XA', 'SAVANNA 2500', 'SY 6483A3 MINI BUS', 'MIRAGE', 'S63', '125 I', 'E 400', 'V 8', 'CMX250C', 'M 7', '3181A', 'GSX 150', 'P5', 'DYNA', '150', 'Z7', 'QUATTRO PORTE', 'LC GX-R 8 SAFARI', '280', 'VERYCA', 'NEON', 'M/L', 'IS 350 COUPE', 'SC 430', 'GA 1021', 'M3', '4', 'ML500', 'VANTAGE', 'CONTINENTAL FLYING SPUR', '523 IA', 'XC 60', 'FRONTIER', 'S130B', 'CAVALIER', 'FZ6-N', 'CENTENNIAL', 'INFINITI M 56', 'XZU710L', '3181', 'VNL 630', 'SCIROCCO', 'ROGUE', 'CG150', 'COBALT', '1', 'INFINITY M 37', 'VIEW VAN', '525', '760', 'A 45', 'LANOS', 'SLK 350', '428 I', '330 (I) CONVERTIBLE', 'CANTER', 'INFINITY FX50', 'VERYCA VAN', 'CDV ZHENZHOU', 'BENZ', 'LIANA', 'J6', 'INFINITY Q60', 'A 5','PICKUP BOX', 'ODYSSEY EXL', '560 SEL', 'MANSORY', 'TR 200M', 'ELANTRA COUPE', 'COLT', 'CD-200T', 'SLR 722', 'S 7', '1843', 'BONGO', 'CAYENNE TURBO', 'CEDRIC', 'S 55', 'EXPRESS', '750 IAL', 'CX 7', 'RS7', 'ALLEGRO', 'CONCORD', 'FLORID', 'EMINA', '190E', 'CPCD30N', 'SL 280', 'SL 600', '308 HATCH BACK', 'AL', 'H1', 'LUMINA S', 'GRAN', 'CTS COUPE', 'C30 D', 'ARGOSY UNIT', 'SOLARA', '190 E', 'CANTER DOUBLE CABIN', 'GL500', 'HILANDER', 'EXCALADE PICK-UP', 'AM SPYDER', 'F 32 420 I', 'EN125', 'SFRAN', 'VF05H70U', '100 CC', 'CAMARO LT', '420 I', 'DB9', 'TRUCKS', 'SINGLE CABIN', 'CB 1300', 'S MAX', '75', 'X5 3.0', 'ASTRA', 'SUNRAY', '711', 'LERADO', 'SX 240', 'TURBO R', '525 IA', 'FD30T', 'VFR1200 FA', 'COLORADO', 'DOKKER', 'SR150', '740 IAL', 'STREET FIGHTER', 'CERATO COUPE', 'JIMMY', 'RS4', 'BLS', '325', 'GRANCABRIO', 'GRAN MARQEZ', 'FINISTERE', 'PRIUS', 'DART', 'CLK 240', 'ELDORADO', 'GRAN CABRIO', 'ROADSTAR', '735 LI', 'FORTWO', 'KREFH', 'PARTNER B9', 'TRAILER', 'ESPACE', 'BIKE SZ16RR ', 'FX COUPE', 'GL 400', '1100', '1831', '206 XR', 'SHUMA', 'EXPETATION ', 'XG 350', 'V6', 'S 6', 'E 250', 'EX 7', 'TURBO', 'SUV 7', '350', 'M1', 'A 5 COUPE', '730 I', '520 (IA)', '640 I SALOON', 'J5', 'MOTOR CYCLE', 'GSX R1000', '900', 'RX 330 STATION', 'L 55', 'ROLLS ROYCE Model', 'VTX1300S', 'PREGIO', 'C 350', 'C36', 'E 150', 'K1300 S', 'CLK 350', 'UPLANDER', 'FD30T3Z', 'U 7', 'C 4', 'ML430', 'DAILY', '3CX', 'MATERIA', 'CHAIRMAN', 'MURCIELAGO', 'QKR', '626LX', 'CLS 400', 'E 350', 'GSR 400', '320 S', 'CT 200H', 'PUNTO', 'CHEVY', 'C 320', 'FB20S', 'CARGO', '25 FD', '300 SE', 'UNICORN', 'TRANS AM', 'C3', '30D -7', '2015', 'DP30NT', 'M 235 I', 'YZF R1M', '143 M', 'QUEST', 'ESCORT', 'CORONA', '207 CC', 'CAYENNE S V8', 'CC', 'PHANTOM LWB', 'DATSUN', 'V80', 'NX', 'MKZ 34', 'NONE', 'KIZASHI', 'GLE 400', 'DENALI', 'XE R SPORT', 'GL 1800 BE', 'M', 'RAM 4WD', 'WIRA', 'VIPER GTS', 'H5.0FT', '156', 'EXPLORER E313', 'RX60 - 30', 'C 30', 'MACAN', '1840', 'ALTIA', 'GOLF R', '135 CC', 'NAVIGATOR', 'E 240', 'H2000', 'SPECTRA', 'GLA 45AMG', 'MKZ', 'PT CRUISER', 'TRAJET', 'CD200TA', 'GL 1800 F', 'GT 125 SCD', 'ATTRAGE GLX', 'H3.OFT', 'GRANDUERE', 'LEXUS 300', 'CBR 600', 'VOYAGER', 'ML400', 'LX 470 LEXUS', 'C 63', 'CLK 230', 'SPRINTER', 'SCIROCO', 'IQ', 'DELICA', 'S 300', 'H 13', 'TD 2000', 'ENZO', '320IA', '730 L', 'RX 400', '70', 'B25 P/VAN', '200', '320 CLK', 'GTI', 'INFINITI G37 X', 'S', 'V8-VANTAGE ', 'V12-VANTAGE', 'RAPIDE S', 'MULSANNE', '400 E', 'L 538', '488 GTB', 'EVOLUTION', 'ML-320', 'KYRON', '535 GT', 'INFINITI EX 37', 'SLK 320', 'GIULIETTA', 'FD25T-16', 'FD70-7', '620I', 'ROVER Model', '200 C', 'G63 AMG', 'IGNIS', 'YGL02A30U', 'TGA 33.480', 'S 600 L', 'SILVER DOWN', 'GL 1800', 'FM 9', 'V 250', 'SZ16S', 'NINJA 250 R', '599 SA APERTA', 'INTEGRA', 'SC', 'K4000', 'H 25', 'SHARAN', '325(I) CONVERTIBLE', '2000', 'SL 350', 'SKID STEERLOADER', 'BACKHOE', '650', '135 I', 'C 250 COUPE', 'GLK 3504M', 'PENTO', 'QUORIS', '323 LX', 'MARINER', 'SCION', 'ML 400', '612 SCAGLIATTI', 'CAPRICE ROYALE', 'SMART', 'SC DX', 'SL 550', '4C', 'CROSS FIRE', 'Z3 ROADSTER', '500 S', 'ADVENTURE', 'ST 1100', 'CLK63', 'IS 430', 'E 63 AMG', 'GENESIS COUPE', 'CL63', 'CBU', 'DP30', '458', 'GSXR 750', 'LAFERRARI', '318 CI', 'SC 300', 'H2L VAN', '308 GT', 'SUPE', 'TRUCK P340', 'CONTINENTAL V8', 'VINTAGE', 'YALE Model', 'LEGEND', 'S 430', 'EQUINOX', 'CBR 1000 RAE', 'Q 8', 'AMAROK', '95', 'GOLD WING', 'TARGA', 'A 5 CABRIOLET', '308 CC', 'CLK 63', '735 (I) LIMOUSINE', 'IS 330', 'C 63 SALOON', 'SANDERO', 'M4', 'SOVEREIEN', '550 I', 'CAPTUR', 'FSR', '1635', '200 SLK', 'F3', 'LX 600 HL', 'ACURA', 'K5', 'X5 35I', 'GALARDO', 'VENZA', 'HD150A', 'FJ XTREME', '160 A', 'MARK 2 ', 'WRANGLER RUBICON', 'A4 SPORTBACK', '940GL', 'MT 07', 'R1 200', 'CL 550', 'ROCKET 111 X', 'XML 6482', 'CAMARO ZL1', 'C 55 AMG', '240 SX', 'SUPRA', 'MX 5', 'XF SV8', 'XJ 900P', 'CRANE', '120H', 'CS 353', '424', 'TG301C', 'D320', 'GLK 280', 'GLA 250', 'COOPER S JCW', '675 LT', 'YZFR 6', 'PRELUDE', 'GEN 2', 'C 8', 'STREET', 'CC 122', 'CK65', '250CC', 'CRETA WAGON', 'B 170', 'ACCORD CROSSTOUR', 'PATROL PICK UP', 'NUBIRA', 'HJ DOXM', 'S 500 COUPE', 'FD50TM1W13', 'ML 55', 'RENEGADE', 'JOURNEY', 'INFINITY Q45', 'F-350', 'LANTIS', 'DAIMLER', 'CPCD 30', '6 V', 'CIVIC TYPE R', 'FX 35', 'S450', '550 I GT', 'MILAN', 'B2200 (P)', '140 A', 'TLX', 'X4', "6 'R'", 'CANTER WITH CRANE', 'ERTIGA', 'SC 4.2 V8', 'PHANTOM SALOON', 'ELECTRIC', '3200 GT', 'BT 50', '320 SL', 'INFINITY G35 COUPE', '760 LI', "6 'S'", 'E16C', 'BRUTALE DRAGSTER 800', 'TURISMO VELOCE 800', 'F3 800', 'TRUMPCHI GA5', 'SKYLINE', 'CL 55', 'CK', '. FORKLIFT', 'CAB', 'SONOMA', 'SLS 500', 'GT3', 'FENG', 'CELICA', 'GS150CD', 'VX 1700', 'MDX', 'VERYCA TRUCK', '330 XI', 'MARQUIS', 'AMANTI', 'LOTUS Model', 'PRIMAVERA 150 ABS', 'CLS 550', 'B2500 ', 'CANTER RECOVERY', 'LEGANZA', 'SLS 63', '-', 'LOCAL', 'G 320', 'BOXER FT 350', 'BOXER FT 300', 'CORSA', 'INFINITY 135', 'PLUMOUTH', 'CPCD', 'MATEZ', 'MOTO RIVALE 800 S', 'MOTO F3 800', 'X6 M', 'GVAN', 'VIBE', 'TRIBECA', 'MESARATI Model', 'I 220', '528 IA', 'ESCURTION', 'S 70', 'VN 900', 'QUTE', 'YZK1021E', 'FREESTAR', 'D7G-2', '330CI  CABRIO', 'COOPER COUNTRYMAN', 'RS 3', 'C 160', '640 GC', 'SUN SEEKER', 'E 450', 'MK X 15 ', 'SZ 150', 'MG6', 'GRAND', 'CBR 250 R', 'PASSENGER', 'URVAN MINIBUS', 'CBF 125', 'GTR SKYLINE', 'VULCAN S ABS', 'DR 650SEL6', 'GLE 63', '728I', 'SCL 500', 'MARCOPOLO  LP613', 'BRAVO', 'HFC 1046K', 'SCANIA Model', 'RC', 'SPORTSTER', 'UD PICKUP', 'CRETA', 'VIPER SRT', 'ESCURSION', 'A4 COUPE', 'C 30 COUPE', '530IA E', 'TFR 54 JSLFM', 'TRIGGER', 'TGX 18.400', 'TGX 18.360', 'A1', 'FIORNIO', 'MOTO F3 675', 'SCRAMBLER', 'NX 200T', 'SHELBY', '427 COBRA', 'LACETTI', '5008 ACT', 'A1 SALOON', 'V50', 'E240-BENZ', 'G10', '330 IAS COUPE', 'ELISE S ', 'CAMARO.', 'MUSTANG.', 'C200 COUPE', 'CHALLENGER. ', 'R NINE T', 'MOKKA COSMO', 'CORVETTE.', 'S-320L', '1000', 'VZR 1800BZL6', 'LW MR', 'E 63', 'GIULIETTA QV', '4500', 'ZHEJIANG', 'LANCER FORTIS', 'DP50CNT', 'CORODOBA SALOON', 'LG30DT', 'DUCATO', 'TRUMPCHI GA3', 'GTR.', 'WA380', 'TGA 33.410', 'INFINITI M35 SALOON', 'RCZ', 'CHARGER.', 'REGAL', 'S1000R', 'NINJA XZ-14R', 'GTX ', 'GLC 250', 'EXTOL', 'XV S950', '110', 'S510', 'SPIDER', 'HPV', 'CLK430', 'RSX', 'NINJA 300', '4X2 SC', 'C35', 'AXOR 1840LS', 'FORTE', 'R300', 'S/W', 'EVORA GTX.', 'GRAND I10', '330 (I) LIMOUSINE', 'F-PACE', 'ASTON MARTIN Model', 'LORSICA', 'F12 BERLINETTA', 'MKT', 'SLK 250', 'COOPER CLUBMAN', 'GLE 450', 'DEER', '440 I', 'CC 1021', 'XEDOS', '260E', 'LPT 1618', 'MG 6', 'NINJA 1000 ', 'CBF 160', 'FIRE FLY', 'DAWN', 'COOPER CABRIO', 'ROUTE VAN', '218 I', 'V40', 'AUMARK', 'F-250', 'GLE 43', 'KANGO', '599 GTB', 'ATS COUPE', '600 N', 'SHELBY.', 'LAGUNA', 'RX 450', 'FD50AT-7', 'CBZ', 'XV', 'U 6', 'CRV AUTO', 'RACERS', 'BENTAYGA', 'HFC 1055', 'BARCHETTA', 'K01H', 'X6-50', 'YETI', 'GS', 'TRUMPCHI GS5', 'WINDSTAR', 'T 4000', 'NX 200', 'WRX-STI', 'J4', 'XP 500', 'XT5', 'Z 126', 'T5', 'EC7RV', 'WALLS', 'SL 400', 'C 43', 'CASCADA', 'BOBCAT Model', 'TELCOLEN', 'ARIZO 7', 'LEVANTE S', 'DISCOVERY SPORT', 'DARK HORSE', 'F 30 318I', 'CT 6', 'A 520T', 'CBR 900', 'CS 75', 'XE 2.0 PRESTIGE', 'GC 2', 'INFINITY Q30', 'TL 250M', 'H2L ', 'BERLINGO', 'BRUTALE 1090 ABS', 'TRAVELLER', 'SF 30', 'MG5', 'JET MAX', 'MULTI VAN', 'CARGO WAN', 'MONSTER 1200', 'H9', 'TENA', 'ADVANCE PLUS', 'SWB 6860', 'K 1600', 'XR 125L', 'E 20P', 'THRILLER', 'TALISMAN', 'HFC 1040K', 'SL 65', 'BRUTALE CORSA', 'ROAD MASTER', 'MUX', 'R 1200 RT', 'F 550', 'F 800 GS', 'MB V', 'AVANTGARDE', 'HFJ7161', 'F40', 'PX 150', 'F12-TDF', 'R 1200 GS', 'SY 0846', 'JUDGE', '430 I', 'TRANSIT', 'KXCT 300', 'C50 E', 'AVANZA COMMERCIAL', '718 CAYMAN S', 'RAPIDE S SALOON', 'MONSTER', 'E 250 AMG ', 'RD SPYDER', 'GT 650 RC', 'VIPER SRT.', 'D & R', 'FORKLIFT EPX30', 'GUZZI', 'VANQUISH', '135', 'ZX 10', 'PAUL SMART 1000', 'ARIZO 5', 'MG 550', 'CARRY', 'BRUTALE 800', 'MT09', 'YG1F2A30', '488 SPIDER', 'VERSYS 1000', '30', 'FD25T', 'THRUXTON 1200R', 'LPT 613/38 BUS', '10.60G', 'FD70Z8', 'QUATTROPORTE S', 'C3000', 'CANTER TANKER', 'MOKKA INNOVATION', '20 FD', 'TIGGO 5', 'D115A BULLDOSER', 'FD 40 KT', 'EC 8', 'CX 3', 'C32', 'TIGGO 3', 'TH6', 'G 400', '216 B3', '420', '5008', 'PIAGGIO', '30 F', 'CPD', 'CRUSER', 'GS 200 T', 'TRUCK/TANKER', 'H6', 'CD 30', 'SC 502', '356 BT5', 'Z 71', 'CHIEFTAIN', '926', 'SC 716', 'JAC', 'FLSTC', '1977', 'SHOVEL', 'M2', 'DIAVEL', 'SCEPTOR', 'C31', 'DRAGSTER RR', '540 I', 'VERYCA PASSENGER VAN', 'CLARK Model', 'BAJAJ Model', 'R 1200 RS', 'HERITAGE', 'CANTER LIGHT PICKUP', 'E2000 PICKUP', 'XML', 'D50 C 5', 'E 31A', '3DX', 'SCORPIO PICKUP', '1500', 'H 30D', 'TERRACAN', 'R 300L', 'M 109', 'GLS 500', 'EXCAVATOR', 'PANIGALE', 'EXR ', '160', 'NPR LIGHT PICKUP', '3201 LIMOUSINE', 'GS F', 'YBR 125C', 'CB 1100', '580 T', 'LG 958', '410 LOADER', '540', 'GLC 300', 'BOXER FT 40', 'ZN50GN', 'B2200 LIGHT', '5028 S', 'MB 524', 'CONTINENTAL GT V8S', 'GT 250 RC', 'ARIZO 3', 'S 90', 'MITO', 'CPCD 70', 'KICKS', 'NPR PICK UP', 'X75 D', 'BJ40L', 'Q2', 'EADO', 'X100', 'CTS V', 'FD100Z8', 'PICK UP LIGHT', 'LAU', 'X100 D', 'X90', 'X', 'OYSTER', 'GLE 43 COUPE', 'E 300 SALOON', 'E 25 M/BUS', 'S75 D SALOON', '848 EVO', 'NINJA ZX-6R', 'S90 D', 'SCANIA AMPHIBIAN BUS', 'LC 500', 'X90 D', 'TOWN CAR MKX U888', 'LCT 17 CONTINENTAL PREMIER', 'DL 320', '966', 'MAYBACH S57', 'DOUBLE CAP', 'S100 D', 'MKS 25', 'ALTIMA COUPE', 'S 85', 'V1', 'V1 MINI TRUCK', 'DS 4', '42-6FGCU25', 'NHQ10', 'EXPERT', 'TFR', 'FERRARI Model', 'CANTER VAN', 'F 100', 'E 300 COUPE', 'S3', 'XL', 'POCSER', 'FM 30', 'FUSO MINIVAN', 'S P 100D', 'E 25 VAN', 'DUTRO', '3CX 14 M2 NM', 'ZINGER', ' F70D-50', 'PARTNER CAR', 'S1000 XR', 'XVS 1300 CU', 'CB 160', '720 S', 'YBR 125 E', 'C 55 SD', 'FH', 'FD30T3CZ', 'Z900', '400 CC', 'G37 COUPE', 'MKC 26', 'M 240I', 'S 450', 'FREEZER VAN', 'C 300 COUPE', '530 I LIMOUSINE', 'B2900', 'Q 50', 'S75 D', 'E 200 COUPE', 'FG20T3', 'DP', '1313', 'ZOE', 'GRW 18', 'WRATH COUPE', 'EXIGE', '440 I SALOON', 'E 43', 'E 400 COUPE', 'MAGNUM', 'GLC 250 4M', '320 I COUPE', 'MINI COUNTRYMAN', 'SQ 5', 'GIULIA', 'AMG GTR', 'G 310', 'DOMINAR 400', 'HP4', '800', 'GC 6', '090 BS', 'CWC TIPPER', 'KENBO H2 ', 'MK 210', '570 S', 'EX 7 STATION', 'B9 COM', 'VELAR 2.0 S', 'ARTEON', 'SCOUT BOBBER', 'CPCD 50M2', 'VEGAS', 'STINGER', '3008 GT', 'F4 R', 'ZNA', '5FD30', 'LS 350', 'C 650 GT', 'GUNNER', 'GX 2', 'SIERRA 3500', 'VELAR SE', '35 SC', 'SHINE', '170', 'ZAFIRA', 'LIGHT PICKUP', 'MPE 500', '40 GT', 'MKC 17', 'TRAMBSHI', 'WRX SALOON', 'VMX', 'RX 350 STATION', '550 I GT SALOON', 'ASTRA COUPE', 'KENBOS6', 'EXTOL VAN', 'VELAR', 'SL 500 SALOON', 'MG 750', 'TGS 40.480', 'TANKER', 'QY25K5I', 'E 24', 'DESIRE', 'HAISE', 'S1000 RR', 'CABSTER', 'G 700', 'H 50T', 'CPCD30T8', '1316 C', 'GLAMOUR', 'E 63 S 4M AMG', 'SANTA-FE 2.4 2WD', 'GSXS 1000 AL8', '812 SUPERFAST', 'ECLIPSE CROSS', 'ALSVIN COMFORT', 'S 560', '2008', 'PATROL NISMO', 'INSINGNA', '950 G', 'R70-30', '1800 CC', 'COOPER COUPE', '25', '430FI', 'SAVANA', 'AVENTADOR S ROADSTER', 'Q X 80', 'KLQ 6129Q', 'CORSA COUPE', 'BJ5081 XCX', '270S', 'CLA 250 AMG', 'INSIGNIA', 'CAMARO ZL1.', 'EMGRADE X7', 'RX5', 'ZS', 'KARIZMA', 'MASTER VAN', 'LF7153D', 'LF7240B', 'S 63 AM', 'LPO 1512-T', 'EAGLE', 'RAPID', 'MAHINDRA XUV 500', 'DB11', 'TV08 TRANSIT', 'RUSH', 'T60', 'SANTAFE', 'EMGRAND X7 SPORTS FLAGSHIP', 'CLA 200', 'GX', 'TGA 18.350', 'DP35MT', 'HIACE BUS', 'S130', 'FD 30 HD', 'RS3 SEDAN', '60Y13', 'ROEWE RX8 (5 SEATER)', 'BOLT', 'TUK TUK TT', 'DS 3', 'FORK LIFT', 'AMG GT ROADSTER', 'HEAVY PICK UP', '420 CONVERTIBLE', 'GRAN CABRIOLET', 'HUNK', 'CX9', 'PARTNER COMBI', 'URUS', 'COOPER S', 'MG 5', 'SY6480A1', 'MODUS', 'TERAMONT', 'NX 300', '50 QX', 'CTX 700', 'CABRIOLET', '748', 'KLQ6123K', '540 C', 'CONTINENTAL COUPE', 'ROZA SW', 'ATTRAGE', '225 I', 'GRAND MA', 'QUATTROPORTE GTS', '55', 'H 30T', 'GLK 300', 'BOOM LOADER', 'SLC 200', 'E-PACE', 'GOLD 19T', 'AR NAET', 'CB 1000', '430 I COUPE', 'XP 530D', 'SL 230 PAGODE', 'ALPINE', 'NC750', 'VITO', 'KINGPIN', 'KLQ 6798', 'KONA', 'FDG6810C', 'SENNA', 'FM 10', 'B40', 'Q 70', 'CS 35', 'FM STX', 'T 600 S', 'Chieftain Darkhorse', 'GS8', '316 Dt/4', 'XUV5', 'DESIIGN', 'CHIRON', '60QX', 'JXK611', '2002', 'DB 50', 'M850I', 'XT4', 'ACTIVA', 'XC40', 'MAJESTIC', '650I', '135 HD SKIN STEEL LOADER', '150 E', 'BEETLE SALOON', 'FLYING SUPER', 'STELVIO 2.0 BZ ', 'CL 50', 'F 450', 'INFINITY QX 30', 'GLC 63', 'XT1200 Z', 'ABARTH SPIDER', 'GOLF HATCH BACK', 'GS4', '428I', 'B 4140', 'TELLURIDE', 'VIPER GTS.', 'CONTINETAL', 'MKC 08', 'XP100 D', 'PICK UP S 24', 'RX HYBRID', 'Q30', 'QX 80', 'XML6121', 'H33 3', 'P360CB6X4ESZ', 'BEETLE COUPE', 'T 700', 'C450', 'MOKKA ', 'INFINITY Q 50', 'CS 95', 'MERIVA', 'STAR HLX', 'EMGRAND GS SP', 'KODIAQ', 'DOBLO', 'T300', '230', 'DISCOVERY SPORT 2.0 HSE', 'MKC', 'ROEWE RX8 (7 SEATER)', 'X7', 'RC 390', 'PEGAS', 'V2', 'GLC 200', 'RX8', 'X2', 'QX 70', 'HS', 'H 40T', ' 226B3', 'TBE 09', 'DZIRE', '220 I', 'REWARD NP', 'BX5', 'GS3', 'XK', 'K1', 'PACEMAN', 'HFC 1062', 'ULTRA 914E', 'UX200', 'PALISADE', 'E 250 ', 'GLC 43', 'BX7', 'D90', 'R140 EXCAVATOR', 'SELTOS', 'GS 450H', 'E 534M AMG', 'MP3 500', 'VIKING', 'A 200', 'SCH1025D', 'FVD20', 'I3 S ELECTRIC', 'INIFINITI G37 COUPE', 'GA8', 'XE 2.0 ', 'IQNIQ', 'CLS 450', 'K400', 'K2', ' 630 I', 'ZSEV ELECTRICAL', 'RANGE ROVER HSE 360 PS', 'FMX14', 'DP100', 'TX VISTA', 'COR120 CORSAIR', 'GRAN SPORT', 'TNT 150', 'SUPER DUKE', 'IRON 883', 'FK617', '235I', '228I', 'ERP20VT', 'CL 250', 'CT5', 'BATWANI', 'GS 7', 'LINEA', 'DX3', '135 I ', 'R 1250 GS', 'C-HR', 'MODEL 3', '120 I ', '436', 'FM 400', 'DX7', 'MK', 'BAILI', 'BJ1088', '140', 'NAUTILUS', 'GLA 200', 'BKE 9', 'DJC', 'XDR', 'GAC', 'SCH6430', 'CS 35 PLUS', 'STEED 400', 'GLA 220', 'CX 30', 'FUSO TRUCK', 'SCH5022XXYD', 'VELOSTER HATCH BACK', 'CS 85', 'AVIATOR', 'MT 10', 'BJ1037V3MX6', 'MTN 690', 'VELOSTER SPORTS CAR', 'FUSO BUS', 'UNI T', 'GENESIS 70', 'AFRICA TWIN', 'GRAND LAND X', 'ZFD50', 'GLA200    ', 'L 405 3.0 SC HSE', 'XP560D', 'IONIQ', ' CLUBMAN', 'BRUTALE 1000R ', 'IGNITOR', '840I', 'PANOZ', 'GLB 250', 'A 35 4M AMG', 'XL 120', 'METRIS', 'FD70', 'S7', '1200', 'SCH1025S', 'XUV 500', '640 I SPORTS', 'GS 5 ', 'DAYTONA'])

use_of_vehicle = st.selectbox('Use of Vehicle', ['PRIVATE', 'COMMERCIAL', 'DELIVERY VEHICLES', 'SCHOOL BUS', 'FORK LIFT', 'PRIVATE/  COMMERCIAL', 'PICK UP DOUBLE CABIN', 'TOUR OPERATION', '4 WD STATION', 'SPORTS CAR', 'RENTACAR', 'CONSTRUCTION EQUIP'])

model_year = st.number_input('Model Year', min_value = 1900,max_value=2099)

chasis_no = st.text_input("Enter the Chasis Number")

regn = st.selectbox('Region',['DUBAI', 'TBR', 'T.B.R', 'AD', 'A.D', 'DUBAI 1871', 'SHJ',
       'AJMAN', 'RAK', 'AJ', 'FUJ', 'Dubai', 'DUBAI ', 'AL AIN',
       'FUJAIRAH', 'A.D.', 'UAQ', 'DUBAI L', 'A D', 'DUBAI K', 'DUBAI  I',
       'CC', 'DUBAI A ', 'DUBAI - D', 'RAS', 'DUBAI  G', 'T B R',
       'DUBAI B', 'A 1', 'DUBAI E', 'CC 17/1', 'ABU DHABI', 'DXB ', 'Shj',
       'SHARJAH', 'DUBAI  F', '40298', 'AJMAN ', 'SHARJHA', 'ADH',
       'DUBAI J', 'DUBAI  E', 'DUBAI I', 'DUBAI  L', 'DUBAI  A',
       'DUBAI H', 'DUBAI  K', 'DUBAI M', 'DUABI', 'ABU DHABI ', 'UMQ',
       'DUBAI     ', 'SHJ ', 'RAK '])

policy_number = st.text_input("Enter the Policy Number")

policy_eff_date = st.date_input('Policy Effective Date',today)

policy_issue_date = st.date_input('Policy Issue Date',today)
policy_expiry_date = st.date_input('Policy Expiry Date',today)

sum_insured = st.number_input('Sum Insured')


premium = st.number_input('Premium')


drv_dob = st.date_input('DOB of Driver',today)
drv_lic = st.date_input('License date of Driver',today)

veh_seats = st.number_input('Number of Seats in Vehicle')


product = st.selectbox('Product',['NOT CLASSIFIED', 'TP', 'STANDARD', 'M 2.5', 'M 2.25', 'M 2019','LUXURY', 'TOURISM', 'RENT A CAR', 'PASSENGER'])
policy_type = st.selectbox('Policy Type',['COMP','TP'])

nationality = st.selectbox('Nationality', ['COMPANY', 'INDIAN', 'CHINESE', 'EMIRATE', 'PHILIPPINE',
       'EGYPTION', 'MOROCCAN', 'UZBEKISTAN', 'BAHRAINI', 'PAKISTANI',
       'RUSSIAN', 'LEBANESE', 'JORDANESE', 'SUDANIS', 'SYRIAN',
       'SIERRA LEONEAN', 'PALESTINE', 'BRITISH',
       'BOSNIAN OR HERZEGOVINIAN', 'GCC COUNTRIES', 'SOUTH AFRICAN',
       'CANADAIAN', 'MALAGASY', 'KOREAN', 'DANISH', 'GERMAN', 'POLISH',
       'KUWAITI', 'IRANIAN', 'ROMANIAN', 'SRI LANKAN', 'FRENCH',
       'AUSTRALIAN', 'KENYA', 'AMERICAN', 'BANGLADESH', 'ITALIAN',
       'COMOROS', 'BULGARIAN', 'MALAYSIAN', 'YEMEN', 'ARMENIAN',
       'ZAMBIAN', 'JAPANESE', 'GREEK, HELLENIC', 'LIBYAN', 'IRAQI',
       'UKRAINIAN', 'THAIL', 'TUNISIA', 'TURKMEN', 'TURKEY', 'AFGHAN',
       'BURKINABÉ', 'ICELANDIC', 'INDONESIAN', 'SAUDI ARABIA', 'NIGERIA',
       'KAZAKHSTANI', 'I-KIRIBATI', 'IRISH', 'ALGERIAN', 'SWEDISH',
       'ZIMBABWE', 'MOLDOVAN', 'PORTUGUESE', 'EUROPEAN',
       'AZERBAIJANI, AZERI', 'TANZANIAN', 'MEXICAN', 'SPANISH',
       'HUNGARIAN, MAGYAR', 'AUSTRIAN', 'FAROESE', 'NETHERLANDS',
       'MOZAMBICAN', 'DOMINICAN', 'COLOMBIAN', 'PALAUAN', 'CZECH',
       'QATARI', 'CROATIAN', 'CHILEAN', 'NEW ZEALAND', 'KYRGYZSTANI',
       'NEPALI, NEPALESE', 'BRAZILIAN', 'OMANI', 'SINGAPORE',
       'ALAND ISLAND', 'U.S. VIRGIN ISLAND', 'SERBIAN', 'JAMAICAN',
       'PERUVIAN', 'CAYMANIAN', 'ALBANIAN', 'SWISS', 'FINNISH',
       'NIGERIEN', 'ERITREA', 'GREENLANDIC', 'GEORGIAN', 'CHANNEL ISLAND',
       'CAMEROONIAN', 'BELARUSIAN', 'RWANDAN', 'MONTENEGRIN', 'SLOVAK',
       'TAIWANESE', 'SAINT LUCIAN', 'LATVIAN', 'BELGIAN', 'ETHOPIA',
       'VENEZUELAN', 'NAURUAN', 'BARBADIAN', 'TRINIDADIAN OR TOBAGONIAN',
       'ARGENTINE', 'SOMALI, SOMALIAN', 'UGANDAN', 'MALAWIAN', 'MAHORAN',
       'SURINAMESE', 'BELIZEAN', 'SVALBARD', 'ECUADORIAN', 'GHANAIAN',
       'LIBERIAN', 'VIETNAMESE', 'LITHUANIAN', 'BAHAMIAN', 'ANGUILLAN',
       'SEYCHELLOIS', 'KITTITIAN OR NEVISIAN', 'ANTIGUAN OR BARBUDAN',
       'REUNIONESE, REUNIONNAIS', 'CHRISTMAS ISLAND', 'CONGOLESE',
       'VATICAN', 'CABO VERDEAN', 'GUYANESE', 'BURMESE', 'ESTONIAN',
       'SLOVENIAN, SLOVENE', 'COCOS ISLAND', 'NICARAGUAN', 'NORWEGIAN',
       'MALTESE', 'HONGKONG', 'MACEDONIAN', 'SALVADORAN', 'SENEGALESE',
       'CHADIAN', 'CUBAN', 'NAMIBIAN', 'MAURITANIAN', 'SAINT HELENIAN',
       'HONDURAN', 'COOK ISLAND', 'GAMBIAN', 'PANAMANIAN', 'CYPRUS',
       'MALIAN, MALINESE', 'PARAGUAYAN', 'MAURITIAN'])

my_inputData = {
    'CUST_ID':[1234456],
    'EXECUTIVE':[executive],
    'BODY':[body],
    'MAKE':[make],
    'MODEL':[model],
    'USE_OF_VEHICLE':[use_of_vehicle],
    'MODEL_YEAR':[model_year],
    'CHASSIS_NO':[chasis_no],
    'REGN':[regn],
    'POLICY_NO':[policy_number],
    'POL_EFF_DATE':[policy_eff_date],
    'POL_EXPIRY_DATE':[policy_expiry_date],
    'SUM INSURED':[sum_insured],
    'POL_ISSUE_DATE':[policy_issue_date],
    'PREMIUM2':[premium],
    'DRV_DOB':[drv_dob],
    'DRV_DLI':[drv_lic],
    'VEH_SEATS':[veh_seats],
    'PRODUCT':[product],
    'POLICYTYPE':[policy_type],
    'Nationality':[nationality]
}
my_dataFrame = pd.DataFrame.from_dict(my_inputData)

encoder = joblib.load("Models/encoder.pkl")


# predictor = joblib.load("Models/randomFC.pkl")
data = bz2.BZ2File('Compressed_Models/comp_randomFC.pbz2','rb')
predictor = pickle.load(data)
#  = joblib.load("Models/synthetic_ml_model.pkl")

if st.button('Predict'):
  my_dataFrame['PolicyDuration'] = (my_dataFrame['POL_EXPIRY_DATE'] - my_dataFrame['POL_ISSUE_DATE'] ).dt.days
  my_dataFrame['EffectivePolicyDuration'] = (my_dataFrame['POL_EXPIRY_DATE'] - my_dataFrame['POL_EFF_DATE'] ).dt.days
  X = my_dataFrame[['EXECUTIVE', 'BODY', 'MAKE', 'MODEL', 'USE_OF_VEHICLE','MODEL_YEAR',  'REGN', 'SUM INSURED',
            'PREMIUM2', 'VEH_SEATS', 'PRODUCT', 'POLICYTYPE','Nationality', 'PolicyDuration','EffectivePolicyDuration']]
  X = X.apply(lambda x: encoder[x.name].transform(x) if x.dtype=='object' else x)
  predict = predictor.predict(X)
  predict_prob = predictor.predict_proba(X)
  conversion_rate = predict_prob[0][0]
  no_conversion_rate = predict_prob[0][1]
  st.info(f"(According to Model Trained on Real Data) Risk of Claim Filling {conversion_rate*100}% \n")
#   predict = predictor1.predict(X)
#   predict_prob1 = predictor1.predict_proba(X)
#   conversion_rate = predict_prob1[0][0]
#   no_conversion_rate = predict_prob1[0][1]
#   st.info(f"(According to Model Trained on Synthetic Data) Risk of Claim Filling {conversion_rate*100}% \n")
  st.balloons()
